apiVersion: apps/v1
kind: Deployment
metadata:
  name: clase-kubernetes-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clase-kubernetes
  template:
    metadata:
      labels:
        app: clase-kubernetes
    spec:
      containers:
      - name: clase-kubernetes
        image: clase-kubernetes:latest
        ports:
        - containerPort: 3000
